kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/bitbucket.org/joshdvir/all-go

steps:
- name: cloner
  pull: default
  image: plugins/git
  settings:
    tags: true
  when:
    event:
    - tag

- name: release
  pull: default
  image: golang:1.10
  commands:
  - make deps
  - "curl -sL https://git.io/goreleaser | bash"
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  when:
    event:
    - tag

- name: docker
  pull: default
  image: plugins/docker:latest
  settings:
    file: Dockerfile
    force_tag: true
    repo: joshdvir/all-go
    tag:
    - "${DRONE_BUILD_NUMBER}"
    - latest
  environment:
    DOCKER_PASSWORD:
      from_secret: docker_password
    DOCKER_USERNAME:
      from_secret: docker_username
  when:
    event:
    - tag

---
kind: secret
name: github_token
get:
  path: secrets/drone/github
  name: token

---
kind: secret
name: docker_password
get:
  path: secrets/drone/docker
  name: docker_password

---
kind: secret
name: docker_username
get:
  path: secrets/drone/docker
  name: docker_username