pipeline:
  # docker:
  #   image: plugins/docker:latest
  #   repo: joshdvir/all-go
  #   tag:
  #     - "${DRONE_BUILD_NUMBER}"
  #     - "latest"
  #   force_tag: true
  #   file: Dockerfile
  #   secrets: [ docker_username, docker_password ]
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  # when:
  #     event: [ push, tag ]

  release:
    image: golang:1.10
    secrets: [ github_token ]
    commands:
      curl -sL https://git.io/goreleaser | bash
    when:
      event: [ push, tag ]