pipeline:
  docker:
    image: plugins/docker:latest
    repo: joshdvir/all-go
    tag:
      - "${DRONE_BUILD_NUMBER}"
      - "latest"
    force_tag: true
    file: Dockerfile
    secrets: [ docker_username, docker_password ]

  release:
    image: golang:1.10
    secrets: [ github_token ]
    commands:
      curl -sL https://git.io/goreleaser | bash --snapshot